### ISSUE TITLE
Client does not try to restore connection to cadence-frontend

### ISSUE THREAD

**Issue by szaluzhskiy** [cadence-workflow/cadence-java-client#523]
During production support. I noticed an issue. When candence-frontend goes down, by some reason. Java client does not try to reconnect to cadence-frontend. 
This situation leads to outage of client-worker node.

The remedy founed by community - https://github.com/motusllc/javautils-cadence/blob/master/javautils-cadence/src/main/java/com/motus/platform/cadence/WorkerStarterSuper.java

**Comment by jchenseated** [comment]
hopefully there is a auto-reconnect feature on cadence-java-client, in our use case we deploy cadence on ECS Fargate, and due to AWS issue, the service can restart for no explicit reason. And in this case all the worker node would lose connection.

Using quartz ^ seems like an overkill

**Comment by szaluzhskiy** [comment]
@jchenseated Seems like unfortunally there is no reconnection option in cadence-java-client at the moment.

**Comment by jchenseated** [comment]
@szaluzhskiy yeah. does the community remedy works for you tho?

**Comment by szaluzhskiy** [comment]
yes, it works

**Comment by longquanzheng** [comment]
Hello @szaluzhskiy @jchenseated which versions are you using? I try to reproduce it with 2.7.8 but it's working as expected. 
What I did:
After running workers and make sure it's up by starting some hello world workflows, shutdown cadence server.
After ~2 minutes,  client throws this exception after about timeout:
```
15:02:07.523 [Activity Poller taskList="HelloActivity", domain="sample": 1] WARN  c.u.cadence.internal.worker.Poller - Failure in thread Activity Poller taskList="HelloActivity", domain="sample": 1
org.apache.thrift.transport.TTransportException: Request timeout after 121011ms
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.throwOnRpcError(WorkflowServiceTChannel.java:546)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.doRemoteCall(WorkflowServiceTChannel.java:519)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.pollForActivityTask(WorkflowServiceTChannel.java:1060)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.lambda$PollForActivityTask$13(WorkflowServiceTChannel.java:1048)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.measureRemoteCall(WorkflowServiceTChannel.java:569)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.PollForActivityTask(WorkflowServiceTChannel.java:1047)
	at com.uber.cadence.internal.worker.ActivityPollTask.poll(ActivityPollTask.java:72)
	at com.uber.cadence.internal.worker.ActivityPollTask.poll(ActivityPollTask.java:34)
	at com.uber.cadence.internal.worker.Poller$PollExecutionTask.run(Poller.java:269)
	at com.uber.cadence.internal.worker.Poller$PollLoopTask.run(Poller.java:240)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
Then I start server again and the client re-connect to the server and is able to run workflows.

**Comment by longquanzheng** [comment]
I guess the problem that rpcLongPollTimeoutMillis by default is 125 seconds(~ 2 minutes). So when server restart, your worker will experience 2 minutes down time. (I think we should decrease the default to 10 seconds, will make a PR later)
If that's the problem you can use 
setRpcLongPollTimeout in ClientOptions to adjust the value.

**Comment by ekomanurung** [comment]
hi @longquanzheng , i also experienced the same issue. with errorResponse id=-1. i also used 2.7.8 version. but still got the same errors. btw are you still facing the same issue @szaluzhskiy @jchenseated? thank you
